### ISSUE TITLE
Compatibility with Citizens and Sentinels 

### ISSUE THREAD

**Issue by tana-to** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#41]
Hello, I recommend enhancing WM compatibility by integrating Citizen and Sentinel plugins. My server initially utilized Quality Armory and Citizen, where I created NPCs equipped with Quality Armory guns. Upon switching to WM, which is significantly superior, I encountered difficulty assigning weapons to my NPCs. Your assistance in resolving this matter would be greatly appreciated.

**Comment by CJCrafter** [comment]
As I told you in discord, use MythicMobs. If you use LibsDisguises with MythicMobs, you can use NPCs to shoot. It works better then citizens ever will.

**Comment by tana-to** [comment]
There is more than 100 maybe 200 highly configured NPCs, it would take a huge huge time to redo them one bye one is there another alternative?

**Comment by CJCrafter** [comment]
You'd have to do this "1 by 1" config regardless. I don't add sentinel support because I cant handle the volume of support requests. I'd love to make many improvements to the plugins, but I don't, because people always want me to do more with a specific feature.

So we have MythicMobs support, which allows custom ai handling, detecting reloads, etc. You can get as advanced as you want using MythicMobs. You can do everything using MythicMobs.

++ Citizens is one of the most broken plugins I've ever used, and I highly recommend never using it on any server.

**Comment by tana-to** [comment]
Hello, 

I completely understand the reason why you do not want to ensure the compatibility of your plugin with citizen. and I agree with you that it's a bad plugin, they just banned me from their discord server for no reason when I was just asking for help. 

the problem is that I have, as I told you, already configured more than 200 NPCs, some with quests, dialogues, journeys and movements to do and it would be extremely long to redo everything with mythical mobs d 'especially since I don't know this plugin well and I'm the only one developing it. 
I therefore still insist (please forgive me for this) that you make your plugin compatible with Citizens and sentinel. 

However, if you are strongly opposed to it, I would like to know in this case if I could do it myself and if so how? 

Thank you in advance for your response, 

fingers crossed, 

have a good day,

tana to

**Comment by CJCrafter** [comment]
Looking at your github history, you've already seen this multiple times:
https://github.com/WeaponMechanics/MechanicsMain/issues/255
